varConfiguration read_input_file(char *filename, varConfiguration VarConfigAux);
varConfiguration read_tracers(varConfiguration VarConfigAux);
varConfiguration read_tracers_ascii(varConfiguration VarConfigAux);
varConfiguration read_tracers_binary(varConfiguration VarConfigAux);
varConfiguration read_tracers_gadget(varConfiguration VarConfigAux);
varConfiguration read_tracers_mxxl(varConfiguration VarConfigAux);
varConfiguration redshift_space_distortions(varConfiguration VarConfigAux);
varConfiguration geometrical_distortions(varConfiguration VarConfigAux);
varConfiguration write_voids(varConfiguration VarConfigAux);
